import { transformArrayToObject } from "utils/arrayTransform";

const config = {
    themes: ['dark', 'light'],
    defaultTheme: 'dark',
    availableLanguages: [
        {key: "javascript", label: "JavaScript (Node.js)", value: "javascript"},
        {key: "python", label: "Python 3", value: "python"},
    ],
    supportedLanguages: transformArrayToObject([
        {exampleId:1, name:'apex'},
        {exampleId:2, name:'azcli'},
        {exampleId:3, name:'bat'},
        {exampleId:4, name:'c'},
        {exampleId:5, name:'clojure'},
        {exampleId:6, name:'coffeescript'},
        {exampleId:7, name:'cpp'},
        {exampleId:8, name:'csharp'},
        {exampleId:9, name:'csp'},
        {exampleId:10, name:'css'},
        {exampleId:11, name:'dockerfile'},
        {exampleId:12, name:'fsharp'},
        {exampleId:13, name:'go'},
        {exampleId:14, name:'graphql'},
        {exampleId:15, name:'handlebars'},
        {exampleId:16, name:'html'},
        {exampleId:17, name:'ini'},
        {exampleId:18, name:'java'},
        {exampleId:19, name:'javascript'},
        {exampleId:20, name:'json'},
        {exampleId:21, name:'kotlin'},
        {exampleId:22, name:'less'},
        {exampleId:23, name:'lua'},
        {exampleId:24, name:'markdown'},
        {exampleId:25, name:'msdax'},
        {exampleId:26, name:'mysql'},
        {exampleId:27, name:'objective-c'},
        {exampleId:28, name:'pascal'},
        {exampleId:29, name:'perl'},
        {exampleId:30, name:'pgsql'},
        {exampleId:31, name:'php'},
        {exampleId:32, name:'plaintext'},
        {exampleId:33, name:'postiats'},
        {exampleId:34, name:'powerquery'},
        {exampleId:35, name:'powershell'},
        {exampleId:36, name:'pug'},
        {exampleId:37, name:'python'},
        {exampleId:38, name:'r'},
        {exampleId:39, name:'razor'},
        {exampleId:40, name:'redis'},
        {exampleId:41, name:'redshift'},
        {exampleId:42, name:'ruby'},
        {exampleId:43, name:'rust'},
        {exampleId:44, name:'sb'},
        {exampleId:45, name:'scheme'},
        {exampleId:46, name:'scss'},
        {exampleId:47, name:'shell'},
        {exampleId:48, name:'sol'},
        {exampleId:49, name:'sql'},
        {exampleId:50, name:'st'},
        {exampleId:51, name:'swift'},
        {exampleId:52, name:'tcl'},
        {exampleId:53, name:'typescript'},
        {exampleId:54, name:'vb'},
        {exampleId:55, name:'xml'},
        {exampleId:56, name:'yaml'}
        ], "name")
}

export default config;
